### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by Juyoo** [suricate-io/suricate#154]
### Subject of the issue
1. Use dependency injecttion by contructor instead of propertie injection
2. Use repository only on the related service
3. Switch class on the right package

#### Issue type
[] Bug
[x] Improvment
[] Documentation
[] Feature

**Comment by yodamad** [comment]
See to use library (such as BeanUtils or Dozer) for painful copy of properties in transformToDto methods for instance

**Comment by Juyoo** [comment]
ok, thanks for these libraries i'll take a look on that :)

**Comment by Juyoo** [comment]
I think i'll go for MapStruct seems to be faster and easier to use then Dozer and support Java configuration instead of XML Files.
You can take a look at this article : http://mariusz.wyszomierski.pl/en/mapping-dozer-vs-mapstruct/

A MapStruct plugin is also available on Intellij and Eclipse that enable the code completion while writing configuration classes.

**Comment by yodamad** [comment]
I was just about to tell you to look at it
