### ISSUE TITLE
Frontend - Add Footer

### ISSUE THREAD

**Issue by Juyoo** [suricate-io/suricate#160]
### Subject of the issue
Add a footer on the angular App with legal mention and app version.

Mention legal : Copyright © 2018, Suricate.io. All rights reserved.

#### Issue type
[] Bug
[] Improvment
[] Documentation
[x] Feature

**Comment by AlexErling** [comment]
Hi, I'm new to open source and was wondering if I could take this on, or let me know if there are any other features you might want. Thanks!

**Comment by yodamad** [comment]
Hi 

Of course you can. Just fork project and push a PR.
Just to know, version must be based on package.json information not hard coded in a .ts file.

Feel free to take any feature you may be interested in, that the spirit of open source 👍

**Comment by AlexErling** [comment]
Okay cool, just to clarify, where should the location of the Footer component be? 
Should it be in src/app/shared/components? 
Just making sure that I am actually helping out, thanks!

**Comment by yodamad** [comment]
Yes it sounds good, create a pages-footer like we did for header for instance

**Comment by yodamad** [comment]
Also, @AlexErling we just merge a PR where we add environment management, it could be cool to also add environment information in that footer :)

**Comment by AlexErling** [comment]
Okay, I will get on that. I've added a footer section, but I am having trouble getting maven installed for the backend.
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project monitoring: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
```
Do you have any thoughts on how I can get this one going? Once I get it up and running then the rest shouldn't be too difficult.

**Comment by yodamad** [comment]
Which java version are u running on ? We tested with 8, lower won't work cause of lambdas, higher can have side effect

@Juyoo : Any idea ?

**Comment by Juyoo** [comment]
I assume you'r trying to run the project with JDK 9.
The maven compiler plugin is not compatible with JDK 9 under the version 3.7.0 (and we are under 3.1.0 version).

As @yodamad said try to run it with the JDK 8.

**Comment by AlexErling** [comment]
Okay, thanks! I will see if I can get it to work.

**Comment by AlexErling** [comment]
Okay, I can see stuff now. I have built out the footer component. Now I am confused where I should put the <pages-footer></pages-footer>. Is it supposed to go in the app.component.html? Any hints? Also, what environment information would want to add so I can put that in? Thanks for helping me out. 
Currently I have:
pages-footer.component.ts
```
import { Component, OnInit } from '@angular/core';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-pages-footer',
  templateUrl: './pages-footer.component.html',
  styleUrls: ['./pages-footer.component.css']
})
export class PagesFooterComponent implements OnInit {

  public version: string = environment.VERSION;

  constructor() { }

  ngOnInit() {
  }

}
```
and 
<p>
pages-footer.component.html:

```
Version {{version}} Copyright © 2018, Suricate.io. All rights reserved.
```
</p>

**Comment by yodamad** [comment]
Open a PR with your implementation, it will be easier to give you feedback directly in the code (if necessary)
Concerning environnement, just add for instance "Version {{env}} {{version}} ...."
