### ISSUE TITLE
Dashboard - Widget execution when adding a new widget

### ISSUE THREAD

**Issue by Juyoo** [suricate-io/suricate#235]
### Subject of the issue
Find a way to execute the new JS Script when adding a widget on the fly, without having to reload the page

#### Issue type
[] Bug
[x] Improvment
[] Documentation
[] Feature

**NB**: Specify labels in right panel also

### Expected behaviour
Tell us what should happen

**Comment by yodamad** [comment]
@Juyoo : delayed to milestone 3.0 ?
