### ISSUE TITLE
Migration to Angular 6+

### ISSUE THREAD

**Issue by yodamad** [suricate-io/suricate#261]
### Subject of the issue
Upgrade to Angular 6 (or newer)

#### Issue type
[] Bug
[X] Improvment
[] Documentation
[] Feature

**NB**: Specify labels in right panel also

**Comment by yodamad** [comment]
Also upgrade also ngx-translate to v10+

**Comment by Juyoo** [comment]
Frontend - Upgrade : @auth0/angular-jwt to v2+
