### ISSUE TITLE
Widget - Configuration Management 

### ISSUE THREAD

**Issue by Juyoo** [suricate-io/suricate#268]
### Subject of the issue
- [x] Add the possiblity to override the global configurations for a widget instance
- [x] Each widget category (Widget repository) should contain the related configuration for this widget (Add Key + type inside the "Description.yml" file)
- [ ] When creating an instance of a widget display if there is a configuration not filled on the global side

#### Issue type
- [ ] Bug
- [ ] Improvment
- [ ] Documentation
- [x] Feature

**NB**: Specify labels in right panel also

**Comment by yodamad** [comment]
@Juyoo : delayed to milestone 3.0 ?
