### ISSUE TITLE
Propose logo

### ISSUE THREAD

**Issue by dee-y** [suricate-io/suricate#285]
Hello, am a graphic designer and i noticed your project does not have a logo yet. I would be glad to contribute a logo to this project if you would have me. Any ideas for the logo are welcomed!. Looking forward to your response. 
Best regards, 
Dee-y.

**Comment by yodamad** [comment]
Hi

Thank you for proposition. We already have one : https://github.com/suricate-io
But feel free to send us new elements

Just keep in mind : 
* We do not have any money :)
* We require that you give back us the rights of all elements

**Comment by yodamad** [comment]
@dee-y still interesting in or should i close the issue ?

**Comment by dee-y** [comment]
Still very much interested!

**Comment by dee-y** [comment]
Will have design for you soon

**Comment by dee-y** [comment]
Hello @yodamad what do you think of this?

![untitled-4-01](https://user-images.githubusercontent.com/36637989/42739440-4e323e58-888f-11e8-88a6-c33274167aa9.png)

**Comment by dee-y** [comment]
It works well also for favicon style

**Comment by yodamad** [comment]
Thanks @dee-y, the logo looks cool, but we agree with @Juyoo that I looks more like a parrot than a suricate.
Any idea to have back our little friendly animal ? :)
