### ISSUE TITLE
Change angular router path for repositories and configurations

### ISSUE THREAD

**Issue by Juyoo** [suricate-io/suricate#322]
**Is your feature request related to a problem? Please describe.**
Related to the double active selection on the menu

**Describe the solution you'd like**
Make a refactor of the angular router path
1 - For repositories transform the url "/widgets/admin/repositories" to "/repositories"
2 - For configurations transform the url "/widgets/admin/configurations" to "/widget-configurations"

**Describe alternatives you've considered**

If possible provide visual sample and code impacts

**NB**: Specify label(s) in right panel to ease requests organization

**Comment by yodamad** [comment]
Add missing label, it has some impacts on backend (API description)

**Comment by yodamad** [comment]
@Juyoo : Milestone 2 or 3 ?

**Comment by Juyoo** [comment]
Milestone 2, it's already done, i'm just waiting for the for the merge of the PR #321

**Comment by Juyoo** [comment]
There are no impacts on backend API, this is just a refactoring of the internal angular routes.
