### ISSUE TITLE
Refactor the management of the global configuration for project widget

### ISSUE THREAD

**Issue by Juyoo** [suricate-io/suricate#401]
**Is your feature request related to a problem? Please describe.**
We need to refactor the management of the global configuration for the project widget, in order to be able to override them without integrating the global configurations in the widget config

If possible provide visual sample and code impacts

**NB**: Specify label(s) in right panel to ease requests organization

**Comment by yodamad** [comment]
Already done to override configuration.
Don't get the point of the issue

**Comment by Juyoo** [comment]
I created it because the first solution does not take into account the previous application.
The old project widgets do not have the global configuration in the backendConfig.

Thus, the execution of the projectWidget that will be migrated will not work.
