### ISSUE TITLE
API Management - Swagger 2

### ISSUE THREAD

**Issue by Juyoo** [suricate-io/suricate#93]
### Subject of the issue
Add Swagger 2 into the project used for document our rest API

#### Issue type
[] Bug
[x] Improvment
[] Documentation
[] Feature

**Comment by milankamboya** [comment]
I would like to contribute on this feature.

**Comment by yodamad** [comment]
Feel free to fork or branch and submit a pull request.
Just don't forget to reference to this issue

**Comment by yodamad** [comment]
@Juyoo : fixed ?

**Comment by Juyoo** [comment]
Yes it's fixed, i close it now
